version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # HTTP server
      - '8080:8080' # WebSocket for TouchDesigner State
      - '8081:8081' # WebSocket for TouchDesigner Elapsed Timer
    environment:
      - RTSP_URL=rtsp://host.docker.internal:554/tdvidstream
    volumes:
      - ./streamer/streams:/app/streamer/streams
