version: '3.8'

services:
  streamer:
    image: node:14
    container_name: eternal-dance-streamer
    working_dir: /app
    volumes:
      - ./streamer:/app
      - ./streamer/streams:/app/streams
    ports:
      - '3000:3000'
    command:
      [
        'sh',
        '-c',
        'apt-get update && apt-get install -y ffmpeg && node docker.js',
      ]
    environment:
      - NODE_ENV=production

volumes:
  streams:
